// GENERATED FILE — do not edit. Run `pnpm run generate:workflow-catalog`.

import type { TermId } from "@carbon/glossary";

export const WORKFLOW_FIELD_HELP: Record<string, TermId> = {
  "action.customer.update.input.accountManagerId": "customer-account-manager",
  "action.customer.update.input.assignee": "assignee",
  "action.customer.update.input.customerTypeId": "customer-type-field",
  "action.item.update.input.assignee": "assignee",
  "action.item.update.input.item": "item",
  "action.job.create.input.dueDate": "job-due-date",
  "action.job.create.input.itemId": "item",
  "action.job.create.input.salesOrderLineId": "job-sales-order-line",
  "action.job.update.input.assignee": "assignee",
  "action.job.update.input.deadlineType": "job-deadline-type",
  "action.job.update.input.dueDate": "job-due-date",
  "action.job.update.input.job": "job",
  "action.job.update.input.priority": "job-priority",
  "action.nonConformance.create.input.nonConformanceTypeId": "issue-issue-type",
  "action.nonConformance.update.input.assignee": "assignee",
  "action.nonConformance.update.input.nonConformance": "nonconformance",
  "action.nonConformance.update.input.nonConformanceTypeId": "issue-issue-type",
  "action.notify.input.aboutId": "workflow-notify-about-record",
  "action.notify.input.aboutType": "workflow-notify-about-record",
  "action.notify.input.channels": "workflow-notify-channels",
  "action.purchaseOrder.create.input.supplierReference":
    "purchase-order-supplier-order-number",
  "action.purchaseOrder.update.input.assignee": "assignee",
  "action.purchaseOrder.update.input.purchaseOrder": "purchase-order",
  "action.purchaseOrder.update.input.supplierReference":
    "purchase-order-supplier-order-number",
  "action.quote.update.input.assignee": "assignee",
  "action.quote.update.input.customerReference": "customer-document-reference",
  "action.quote.update.input.expirationDate": "quote-expiration-date",
  "action.quote.update.input.quote": "quote",
  "action.receipt.update.input.assignee": "assignee",
  "action.receipt.update.input.receipt": "receipt",
  "action.salesOrder.create.input.customerReference":
    "customer-document-reference",
  "action.salesOrder.update.input.assignee": "assignee",
  "action.salesOrder.update.input.customerReference":
    "customer-document-reference",
  "action.salesOrder.update.input.salesOrder": "sales-order",
  "action.shipment.update.input.assignee": "assignee",
  "action.shipment.update.input.shipment": "shipment",
  "action.shipment.update.input.shippingMethodId": "shipping-method",
  "action.supplier.update.input.accountManagerId": "supplier-account-manager",
  "action.supplier.update.input.assignee": "assignee",
  "action.supplier.update.input.supplierTypeId": "supplier-type-field",
  "action.webhook.input.body": "workflow-webhook-body",
  "action.webhook.input.headers": "workflow-webhook-headers",
  "action.webhook.input.method": "workflow-webhook-method",
  "action.webhook.input.url": "workflow-webhook-url",
  "operation.item.quantityOnHand.input.item": "item",
  "operation.job.earliestOperationStart.input.job": "job",
  "operation.job.latestOperationEnd.input.job": "job",
  "operation.job.openOperationCount.input.job": "job",
  "operation.job.operationCount.input.job": "job",
  "operation.job.scrapPercentage.input.job": "job",
  "operation.job.totalScrapQuantity.input.job": "job",
  "operation.nonConformance.openTaskCount.input.nonConformance":
    "nonconformance",
  "operation.purchaseOrder.lineCount.input.purchaseOrder": "purchase-order",
  "operation.purchaseOrder.total.input.purchaseOrder": "purchase-order",
  "operation.quote.total.input.quote": "quote",
  "operation.receipt.lineCount.input.receipt": "receipt",
  "operation.salesOrder.lineCount.input.salesOrder": "sales-order",
  "operation.salesOrder.total.input.salesOrder": "sales-order",
  "operation.shipment.lineCount.input.shipment": "shipment"
};
