// GENERATED FILE — do not edit. Run `pnpm run generate:workflow-catalog`.

import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

export const WORKFLOW_LABELS: Record<string, MessageDescriptor> = {
  "action.customer.update.input.accountManagerId": msg`Account manager`,
  "action.customer.update.input.assignee": msg`Assignee`,
  "action.customer.update.input.customer": msg`Customer`,
  "action.customer.update.input.customerTypeId": msg`Type`,
  "action.item.update.input.assignee": msg`Assignee`,
  "action.item.update.input.item": msg`Item`,
  "action.item.update.input.name": msg`Name`,
  "action.job.create.input.dueDate": msg`Due date`,
  "action.job.create.input.itemId": msg`Item`,
  "action.job.create.input.quantity": msg`Quantity`,
  "action.job.create.input.salesOrderLineId": msg`Sales order line`,
  "action.job.update.input.assignee": msg`Assignee`,
  "action.job.update.input.deadlineType": msg`Deadline type`,
  "action.job.update.input.dueDate": msg`Due date`,
  "action.job.update.input.job": msg`Job`,
  "action.job.update.input.priority": msg`Priority`,
  "action.job.update.input.startDate": msg`Start date`,
  "action.nonConformance.create.input.description": msg`Description`,
  "action.nonConformance.create.input.locationId": msg`Location`,
  "action.nonConformance.create.input.name": msg`Title`,
  "action.nonConformance.create.input.nonConformanceTypeId": msg`Type`,
  "action.nonConformance.create.input.openDate": msg`Open date`,
  "action.nonConformance.create.input.priority": msg`Priority`,
  "action.nonConformance.create.input.source": msg`Source`,
  "action.nonConformance.update.input.assignee": msg`Assignee`,
  "action.nonConformance.update.input.dueDate": msg`Due date`,
  "action.nonConformance.update.input.nonConformance": msg`Issue`,
  "action.nonConformance.update.input.nonConformanceTypeId": msg`Type`,
  "action.nonConformance.update.input.priority": msg`Priority`,
  "action.notify.input.aboutId": msg`About`,
  "action.notify.input.aboutType": msg`Kind of record`,
  "action.notify.input.channels": msg`Notification type`,
  "action.notify.input.message": msg`Message`,
  "action.notify.input.role": msg`Group`,
  "action.notify.input.subject": msg`Subject`,
  "action.notify.input.user": msg`Person`,
  "action.purchaseOrder.create.input.orderDate": msg`Order date`,
  "action.purchaseOrder.create.input.supplierId": msg`Supplier`,
  "action.purchaseOrder.create.input.supplierReference": msg`Supplier reference`,
  "action.purchaseOrder.update.input.assignee": msg`Assignee`,
  "action.purchaseOrder.update.input.orderDate": msg`Order date`,
  "action.purchaseOrder.update.input.purchaseOrder": msg`Purchase order`,
  "action.purchaseOrder.update.input.supplierReference": msg`Supplier reference`,
  "action.quote.update.input.assignee": msg`Assignee`,
  "action.quote.update.input.customerReference": msg`Customer reference`,
  "action.quote.update.input.dueDate": msg`Due date`,
  "action.quote.update.input.estimatorId": msg`Estimator`,
  "action.quote.update.input.expirationDate": msg`Expiration date`,
  "action.quote.update.input.quote": msg`Quote`,
  "action.quote.update.input.salesPersonId": msg`Salesperson`,
  "action.receipt.update.input.assignee": msg`Assignee`,
  "action.receipt.update.input.receipt": msg`Receipt`,
  "action.salesOrder.create.input.customerId": msg`Customer`,
  "action.salesOrder.create.input.customerReference": msg`Customer reference`,
  "action.salesOrder.create.input.orderDate": msg`Order date`,
  "action.salesOrder.update.input.assignee": msg`Assignee`,
  "action.salesOrder.update.input.customerReference": msg`Customer reference`,
  "action.salesOrder.update.input.orderDate": msg`Order date`,
  "action.salesOrder.update.input.salesOrder": msg`Sales order`,
  "action.salesOrder.update.input.salesPersonId": msg`Salesperson`,
  "action.shipment.update.input.assignee": msg`Assignee`,
  "action.shipment.update.input.shipment": msg`Shipment`,
  "action.shipment.update.input.shippingMethodId": msg`Shipping method`,
  "action.shipment.update.input.trackingNumber": msg`Tracking number`,
  "action.supplier.update.input.accountManagerId": msg`Account manager`,
  "action.supplier.update.input.assignee": msg`Assignee`,
  "action.supplier.update.input.supplier": msg`Supplier`,
  "action.supplier.update.input.supplierTypeId": msg`Type`,
  "action.webhook.input.body": msg`Body`,
  "action.webhook.input.headers": msg`Headers`,
  "action.webhook.input.method": msg`Method`,
  "action.webhook.input.url": msg`URL`,
  "customer.accountManagerId.changed": msg`A customer's account manager changes`,
  "customer.assignee.changed": msg`A customer's assignee changes`,
  "customer.created": msg`A customer is created`,
  "customer.currencyCode.changed": msg`A customer's currency changes`,
  "customer.customerStatusId.changed": msg`A customer's status changes`,
  "customer.customerTypeId.changed": msg`A customer's type changes`,
  "customer.deleted": msg`A customer is deleted`,
  "customer.name.changed": msg`A customer's name changes`,
  "customer.salesContactId.changed": msg`A customer's sales contact changes`,
  "customer.update": msg`Update a customer`,
  "entity.customer": msg`Customer`,
  "entity.customer.accountManagerId": msg`Account manager`,
  "entity.customer.assignee": msg`Assignee`,
  "entity.customer.createdAt": msg`Created at`,
  "entity.customer.createdBy": msg`Created by`,
  "entity.customer.currencyCode": msg`Currency`,
  "entity.customer.customerStatusId": msg`Status`,
  "entity.customer.customerTypeId": msg`Type`,
  "entity.customer.defaultCc": msg`Default cc`,
  "entity.customer.fax": msg`Fax`,
  "entity.customer.id": msg`Id`,
  "entity.customer.intercompanyCompanyId": msg`Intercompany company`,
  "entity.customer.logo": msg`Logo`,
  "entity.customer.name": msg`Name`,
  "entity.customer.phone": msg`Phone`,
  "entity.customer.readableId": msg`Readable`,
  "entity.customer.salesContactId": msg`Sales contact`,
  "entity.customer.tags": msg`Tags`,
  "entity.customer.taxPercent": msg`Tax percent`,
  "entity.customer.website": msg`Website`,
  "entity.group": msg`Group`,
  "entity.group.createdAt": msg`Created at`,
  "entity.group.id": msg`Id`,
  "entity.group.isCustomerOrgGroup": msg`Is customer org group`,
  "entity.group.isCustomerTypeGroup": msg`Is customer type group`,
  "entity.group.isEmployeeTypeGroup": msg`Is employee type group`,
  "entity.group.isIdentityGroup": msg`Is identity group`,
  "entity.group.isSupplierOrgGroup": msg`Is supplier org group`,
  "entity.group.isSupplierTypeGroup": msg`Is supplier type group`,
  "entity.group.name": msg`Name`,
  "entity.item": msg`Item`,
  "entity.item.active": msg`Active`,
  "entity.item.assignee": msg`Assignee`,
  "entity.item.changeOrderId": msg`Change order`,
  "entity.item.createdAt": msg`Created at`,
  "entity.item.createdBy": msg`Created by`,
  "entity.item.defaultMethodType": msg`Default method type`,
  "entity.item.description": msg`Description`,
  "entity.item.id": msg`Id`,
  "entity.item.itemTrackingType": msg`Tracking type`,
  "entity.item.modelUploadId": msg`Model upload`,
  "entity.item.mpn": msg`Mpn`,
  "entity.item.name": msg`Name`,
  "entity.item.notes": msg`Notes`,
  "entity.item.readableId": msg`Readable`,
  "entity.item.readableIdWithRevision": msg`Readable id with revision`,
  "entity.item.replenishmentSystem": msg`Replenishment system`,
  "entity.item.revision": msg`Revision`,
  "entity.item.revisionStatus": msg`Revision status`,
  "entity.item.sourcingType": msg`Sourcing type`,
  "entity.item.thumbnailPath": msg`Thumbnail path`,
  "entity.item.trackingMethod": msg`Tracking method`,
  "entity.item.type": msg`Type`,
  "entity.item.unitOfMeasureCode": msg`Unit of measure`,
  "entity.job": msg`Job`,
  "entity.job.actualTime": msg`Actual time`,
  "entity.job.assignee": msg`Assignee`,
  "entity.job.completedDate": msg`Completed date`,
  "entity.job.configuration": msg`Configuration`,
  "entity.job.createdAt": msg`Created at`,
  "entity.job.createdBy": msg`Created by`,
  "entity.job.customerId": msg`Customer`,
  "entity.job.deadlineType": msg`Deadline type`,
  "entity.job.dueDate": msg`Due date`,
  "entity.job.estimatedTime": msg`Estimated time`,
  "entity.job.id": msg`Id`,
  "entity.job.itemId": msg`Item`,
  "entity.job.jobId": msg`Job`,
  "entity.job.locationId": msg`Location`,
  "entity.job.modelUploadId": msg`Model upload`,
  "entity.job.notes": msg`Notes`,
  "entity.job.priority": msg`Priority`,
  "entity.job.productionQuantity": msg`Production quantity`,
  "entity.job.projectedCompletionAt": msg`Projected completion at`,
  "entity.job.quantity": msg`Quantity`,
  "entity.job.quantityComplete": msg`Quantity complete`,
  "entity.job.quantityReceivedToInventory": msg`Quantity received to inventory`,
  "entity.job.quantityShipped": msg`Quantity shipped`,
  "entity.job.quoteId": msg`Quote`,
  "entity.job.quoteLineId": msg`Quote line`,
  "entity.job.releasedDate": msg`Released date`,
  "entity.job.salesOrderId": msg`Sales order`,
  "entity.job.salesOrderLineId": msg`Sales order line`,
  "entity.job.scheduleOutdatedAt": msg`Schedule outdated at`,
  "entity.job.scheduleOutdatedReason": msg`Schedule outdated reason`,
  "entity.job.scrapQuantity": msg`Scrap quantity`,
  "entity.job.secondsToComplete": msg`Seconds to complete`,
  "entity.job.startDate": msg`Start date`,
  "entity.job.status": msg`Status`,
  "entity.job.storageUnitId": msg`Storage unit`,
  "entity.job.tags": msg`Tags`,
  "entity.job.unitOfMeasureCode": msg`Unit of measure code`,
  "entity.jobOperation": msg`Job operation`,
  "entity.jobOperation.assemblyInstructionId": msg`Assembly instruction`,
  "entity.jobOperation.assignee": msg`Assignee`,
  "entity.jobOperation.conflictReason": msg`Conflict reason`,
  "entity.jobOperation.createdAt": msg`Created at`,
  "entity.jobOperation.createdBy": msg`Created by`,
  "entity.jobOperation.description": msg`Description`,
  "entity.jobOperation.dueDate": msg`Due date`,
  "entity.jobOperation.hasConflict": msg`Has conflict`,
  "entity.jobOperation.id": msg`Id`,
  "entity.jobOperation.inspectionDocumentId": msg`Inspection document`,
  "entity.jobOperation.jobId": msg`Job`,
  "entity.jobOperation.jobMakeMethodId": msg`Job make method`,
  "entity.jobOperation.jobOperationBatchId": msg`Job operation batch`,
  "entity.jobOperation.laborRate": msg`Labor rate`,
  "entity.jobOperation.laborTime": msg`Labor time`,
  "entity.jobOperation.laborUnit": msg`Labor unit`,
  "entity.jobOperation.machineRate": msg`Machine rate`,
  "entity.jobOperation.machineTime": msg`Machine time`,
  "entity.jobOperation.machineUnit": msg`Machine unit`,
  "entity.jobOperation.manuallyScheduled": msg`Manually scheduled`,
  "entity.jobOperation.operationLeadTime": msg`Operation lead time`,
  "entity.jobOperation.operationMinimumCost": msg`Operation minimum cost`,
  "entity.jobOperation.operationOrder": msg`Operation order`,
  "entity.jobOperation.operationQuantity": msg`Operation quantity`,
  "entity.jobOperation.operationSupplierProcessId": msg`Operation supplier process`,
  "entity.jobOperation.operationType": msg`Operation type`,
  "entity.jobOperation.operationUnitCost": msg`Operation unit cost`,
  "entity.jobOperation.order": msg`Order`,
  "entity.jobOperation.overheadRate": msg`Overhead rate`,
  "entity.jobOperation.priority": msg`Priority`,
  "entity.jobOperation.procedureId": msg`Procedure`,
  "entity.jobOperation.processId": msg`Process`,
  "entity.jobOperation.projectedCompletionAt": msg`Projected completion at`,
  "entity.jobOperation.quantityComplete": msg`Quantity complete`,
  "entity.jobOperation.quantityReworked": msg`Quantity reworked`,
  "entity.jobOperation.quantityScrapped": msg`Quantity scrapped`,
  "entity.jobOperation.readyAt": msg`Ready at`,
  "entity.jobOperation.reworkId": msg`Rework`,
  "entity.jobOperation.setupTime": msg`Setup time`,
  "entity.jobOperation.setupUnit": msg`Setup unit`,
  "entity.jobOperation.startDate": msg`Start date`,
  "entity.jobOperation.status": msg`Status`,
  "entity.jobOperation.tags": msg`Tags`,
  "entity.jobOperation.targetQuantity": msg`Target quantity`,
  "entity.jobOperation.workCenterId": msg`Work center`,
  "entity.jobOperation.workInstruction": msg`Work instruction`,
  "entity.location": msg`Location`,
  "entity.location.addressLine1": msg`Address line1`,
  "entity.location.addressLine2": msg`Address line2`,
  "entity.location.city": msg`City`,
  "entity.location.code": msg`Code`,
  "entity.location.countryCode": msg`Country code`,
  "entity.location.createdAt": msg`Created at`,
  "entity.location.createdBy": msg`Created by`,
  "entity.location.id": msg`Id`,
  "entity.location.latitude": msg`Latitude`,
  "entity.location.longitude": msg`Longitude`,
  "entity.location.name": msg`Name`,
  "entity.location.postalCode": msg`Postal code`,
  "entity.location.requiresStaffing": msg`Requires staffing`,
  "entity.location.stateProvince": msg`State province`,
  "entity.location.tags": msg`Tags`,
  "entity.location.timezone": msg`Timezone`,
  "entity.nonConformance": msg`Issue`,
  "entity.nonConformance.approvalRequirements": msg`Approval requirements`,
  "entity.nonConformance.assignee": msg`Assignee`,
  "entity.nonConformance.closeDate": msg`Close date`,
  "entity.nonConformance.content": msg`Content`,
  "entity.nonConformance.createdAt": msg`Created at`,
  "entity.nonConformance.createdBy": msg`Created by`,
  "entity.nonConformance.description": msg`Description`,
  "entity.nonConformance.dueDate": msg`Due date`,
  "entity.nonConformance.id": msg`Id`,
  "entity.nonConformance.locationId": msg`Location`,
  "entity.nonConformance.name": msg`Name`,
  "entity.nonConformance.nonConformanceId": msg`Non conformance`,
  "entity.nonConformance.nonConformanceTypeId": msg`Type`,
  "entity.nonConformance.nonConformanceWorkflowId": msg`Non conformance workflow`,
  "entity.nonConformance.openDate": msg`Open date`,
  "entity.nonConformance.priority": msg`Priority`,
  "entity.nonConformance.quantity": msg`Quantity`,
  "entity.nonConformance.requiredActionIds": msg`Required action ids`,
  "entity.nonConformance.source": msg`Source`,
  "entity.nonConformance.status": msg`Status`,
  "entity.nonConformance.tags": msg`Tags`,
  "entity.nonConformanceType": msg`Issue type`,
  "entity.nonConformanceType.createdAt": msg`Created at`,
  "entity.nonConformanceType.createdBy": msg`Created by`,
  "entity.nonConformanceType.id": msg`Id`,
  "entity.nonConformanceType.name": msg`Name`,
  "entity.purchaseInvoice": msg`Purchase invoice`,
  "entity.purchaseInvoice.assignee": msg`Assignee`,
  "entity.purchaseInvoice.createdAt": msg`Created at`,
  "entity.purchaseInvoice.createdBy": msg`Created by`,
  "entity.purchaseInvoice.currencyCode": msg`Currency code`,
  "entity.purchaseInvoice.dateDue": msg`Date due`,
  "entity.purchaseInvoice.dateIssued": msg`Date issued`,
  "entity.purchaseInvoice.datePaid": msg`Date paid`,
  "entity.purchaseInvoice.exchangeRate": msg`Exchange rate`,
  "entity.purchaseInvoice.exchangeRateUpdatedAt": msg`Exchange rate updated at`,
  "entity.purchaseInvoice.id": msg`Id`,
  "entity.purchaseInvoice.internalNotes": msg`Internal notes`,
  "entity.purchaseInvoice.invoiceId": msg`Invoice`,
  "entity.purchaseInvoice.invoiceSupplierContactId": msg`Invoice supplier contact`,
  "entity.purchaseInvoice.invoiceSupplierId": msg`Invoice supplier`,
  "entity.purchaseInvoice.invoiceSupplierLocationId": msg`Invoice supplier location`,
  "entity.purchaseInvoice.locationId": msg`Location`,
  "entity.purchaseInvoice.paymentTermId": msg`Payment term`,
  "entity.purchaseInvoice.postingDate": msg`Posting date`,
  "entity.purchaseInvoice.status": msg`Status`,
  "entity.purchaseInvoice.subtotal": msg`Subtotal`,
  "entity.purchaseInvoice.supplierId": msg`Supplier`,
  "entity.purchaseInvoice.supplierInteractionId": msg`Supplier interaction`,
  "entity.purchaseInvoice.supplierReference": msg`Supplier reference`,
  "entity.purchaseInvoice.tags": msg`Tags`,
  "entity.purchaseInvoice.totalAmount": msg`Total amount`,
  "entity.purchaseInvoice.totalDiscount": msg`Total discount`,
  "entity.purchaseInvoice.totalTax": msg`Total tax`,
  "entity.purchaseOrder": msg`Purchase order`,
  "entity.purchaseOrder.assignee": msg`Assignee`,
  "entity.purchaseOrder.closedAt": msg`Closed at`,
  "entity.purchaseOrder.closedBy": msg`Closed by`,
  "entity.purchaseOrder.createdAt": msg`Created at`,
  "entity.purchaseOrder.createdBy": msg`Created by`,
  "entity.purchaseOrder.currencyCode": msg`Currency code`,
  "entity.purchaseOrder.exchangeRate": msg`Exchange rate`,
  "entity.purchaseOrder.exchangeRateUpdatedAt": msg`Exchange rate updated at`,
  "entity.purchaseOrder.externalNotes": msg`External notes`,
  "entity.purchaseOrder.id": msg`Id`,
  "entity.purchaseOrder.internalNotes": msg`Internal notes`,
  "entity.purchaseOrder.jobId": msg`Job`,
  "entity.purchaseOrder.jobReadableId": msg`Job readable`,
  "entity.purchaseOrder.orderDate": msg`Order date`,
  "entity.purchaseOrder.purchaseOrderId": msg`Purchase order`,
  "entity.purchaseOrder.purchaseOrderType": msg`Type`,
  "entity.purchaseOrder.revisionId": msg`Revision`,
  "entity.purchaseOrder.status": msg`Status`,
  "entity.purchaseOrder.supplierContactId": msg`Supplier contact`,
  "entity.purchaseOrder.supplierId": msg`Supplier`,
  "entity.purchaseOrder.supplierInteractionId": msg`Supplier interaction`,
  "entity.purchaseOrder.supplierLocationId": msg`Supplier location`,
  "entity.purchaseOrder.supplierReference": msg`Supplier reference`,
  "entity.purchaseOrder.tags": msg`Tags`,
  "entity.quote": msg`Quote`,
  "entity.quote.assignee": msg`Assignee`,
  "entity.quote.completedDate": msg`Completed date`,
  "entity.quote.createdAt": msg`Created at`,
  "entity.quote.createdBy": msg`Created by`,
  "entity.quote.currencyCode": msg`Currency code`,
  "entity.quote.customerContactId": msg`Customer contact`,
  "entity.quote.customerEngineeringContactId": msg`Customer engineering contact`,
  "entity.quote.customerId": msg`Customer`,
  "entity.quote.customerLocationId": msg`Customer location`,
  "entity.quote.customerReference": msg`Customer reference`,
  "entity.quote.digitalQuoteAcceptedBy": msg`Digital quote accepted by`,
  "entity.quote.digitalQuoteAcceptedByEmail": msg`Digital quote accepted by email`,
  "entity.quote.digitalQuoteRejectedBy": msg`Digital quote rejected by`,
  "entity.quote.digitalQuoteRejectedByEmail": msg`Digital quote rejected by email`,
  "entity.quote.dueDate": msg`Due date`,
  "entity.quote.estimatorId": msg`Estimator`,
  "entity.quote.exchangeRate": msg`Exchange rate`,
  "entity.quote.exchangeRateUpdatedAt": msg`Exchange rate updated at`,
  "entity.quote.expirationDate": msg`Expiration date`,
  "entity.quote.externalLinkId": msg`External link`,
  "entity.quote.externalNotes": msg`External notes`,
  "entity.quote.id": msg`Id`,
  "entity.quote.internalNotes": msg`Internal notes`,
  "entity.quote.locationId": msg`Location`,
  "entity.quote.opportunityId": msg`Opportunity`,
  "entity.quote.quoteId": msg`Quote`,
  "entity.quote.revisionId": msg`Revision`,
  "entity.quote.salesPersonId": msg`Salesperson`,
  "entity.quote.status": msg`Status`,
  "entity.quote.tags": msg`Tags`,
  "entity.receipt": msg`Receipt`,
  "entity.receipt.assignee": msg`Assignee`,
  "entity.receipt.createdAt": msg`Created at`,
  "entity.receipt.createdBy": msg`Created by`,
  "entity.receipt.externalDocumentId": msg`External document`,
  "entity.receipt.id": msg`Id`,
  "entity.receipt.internalNotes": msg`Internal notes`,
  "entity.receipt.invoiced": msg`Invoiced`,
  "entity.receipt.locationId": msg`Location`,
  "entity.receipt.postedBy": msg`Posted by`,
  "entity.receipt.postingDate": msg`Posting date`,
  "entity.receipt.receiptId": msg`Receipt`,
  "entity.receipt.sourceDocument": msg`Source document`,
  "entity.receipt.sourceDocumentId": msg`Source document`,
  "entity.receipt.sourceDocumentReadableId": msg`Source document readable`,
  "entity.receipt.status": msg`Status`,
  "entity.receipt.supplierId": msg`Supplier`,
  "entity.receipt.supplierInteractionId": msg`Supplier interaction`,
  "entity.receipt.tags": msg`Tags`,
  "entity.salesInvoice": msg`Sales invoice`,
  "entity.salesInvoice.assignee": msg`Assignee`,
  "entity.salesInvoice.createdAt": msg`Created at`,
  "entity.salesInvoice.createdBy": msg`Created by`,
  "entity.salesInvoice.currencyCode": msg`Currency code`,
  "entity.salesInvoice.customerId": msg`Customer`,
  "entity.salesInvoice.customerReference": msg`Customer reference`,
  "entity.salesInvoice.dateDue": msg`Date due`,
  "entity.salesInvoice.dateIssued": msg`Date issued`,
  "entity.salesInvoice.datePaid": msg`Date paid`,
  "entity.salesInvoice.exchangeRate": msg`Exchange rate`,
  "entity.salesInvoice.exchangeRateUpdatedAt": msg`Exchange rate updated at`,
  "entity.salesInvoice.externalNotes": msg`External notes`,
  "entity.salesInvoice.id": msg`Id`,
  "entity.salesInvoice.internalNotes": msg`Internal notes`,
  "entity.salesInvoice.invoiceCustomerContactId": msg`Invoice customer contact`,
  "entity.salesInvoice.invoiceCustomerId": msg`Invoice customer`,
  "entity.salesInvoice.invoiceCustomerLocationId": msg`Invoice customer location`,
  "entity.salesInvoice.invoiceId": msg`Invoice`,
  "entity.salesInvoice.locationId": msg`Location`,
  "entity.salesInvoice.opportunityId": msg`Opportunity`,
  "entity.salesInvoice.paymentTermId": msg`Payment term`,
  "entity.salesInvoice.postingDate": msg`Posting date`,
  "entity.salesInvoice.shipmentId": msg`Shipment`,
  "entity.salesInvoice.status": msg`Status`,
  "entity.salesInvoice.subtotal": msg`Subtotal`,
  "entity.salesInvoice.tags": msg`Tags`,
  "entity.salesInvoice.totalAmount": msg`Total amount`,
  "entity.salesInvoice.totalDiscount": msg`Total discount`,
  "entity.salesInvoice.totalTax": msg`Total tax`,
  "entity.salesOrder": msg`Sales order`,
  "entity.salesOrder.assignee": msg`Assignee`,
  "entity.salesOrder.closedAt": msg`Closed at`,
  "entity.salesOrder.closedBy": msg`Closed by`,
  "entity.salesOrder.completedDate": msg`Completed date`,
  "entity.salesOrder.createdAt": msg`Created at`,
  "entity.salesOrder.createdBy": msg`Created by`,
  "entity.salesOrder.currencyCode": msg`Currency code`,
  "entity.salesOrder.customerContactId": msg`Customer contact`,
  "entity.salesOrder.customerEngineeringContactId": msg`Customer engineering contact`,
  "entity.salesOrder.customerId": msg`Customer`,
  "entity.salesOrder.customerLocationId": msg`Customer location`,
  "entity.salesOrder.customerReference": msg`Customer reference`,
  "entity.salesOrder.exchangeRate": msg`Exchange rate`,
  "entity.salesOrder.exchangeRateUpdatedAt": msg`Exchange rate updated at`,
  "entity.salesOrder.externalNotes": msg`External notes`,
  "entity.salesOrder.id": msg`Id`,
  "entity.salesOrder.internalNotes": msg`Internal notes`,
  "entity.salesOrder.locationId": msg`Location`,
  "entity.salesOrder.opportunityId": msg`Opportunity`,
  "entity.salesOrder.orderDate": msg`Order date`,
  "entity.salesOrder.revisionId": msg`Revision`,
  "entity.salesOrder.salesOrderId": msg`Sales order`,
  "entity.salesOrder.salesPersonId": msg`Salesperson`,
  "entity.salesOrder.sentCompleteDate": msg`Sent complete date`,
  "entity.salesOrder.status": msg`Status`,
  "entity.shipment": msg`Shipment`,
  "entity.shipment.assignee": msg`Assignee`,
  "entity.shipment.createdAt": msg`Created at`,
  "entity.shipment.createdBy": msg`Created by`,
  "entity.shipment.customerId": msg`Customer`,
  "entity.shipment.externalDocumentId": msg`External document`,
  "entity.shipment.externalNotes": msg`External notes`,
  "entity.shipment.id": msg`Id`,
  "entity.shipment.internalNotes": msg`Internal notes`,
  "entity.shipment.invoiced": msg`Invoiced`,
  "entity.shipment.locationId": msg`Location`,
  "entity.shipment.opportunityId": msg`Opportunity`,
  "entity.shipment.postedBy": msg`Posted by`,
  "entity.shipment.postingDate": msg`Posting date`,
  "entity.shipment.shipmentId": msg`Shipment`,
  "entity.shipment.shippingMethodId": msg`Shipping method`,
  "entity.shipment.sourceDocument": msg`Source document`,
  "entity.shipment.sourceDocumentId": msg`Source document`,
  "entity.shipment.sourceDocumentReadableId": msg`Source document readable`,
  "entity.shipment.status": msg`Status`,
  "entity.shipment.supplierId": msg`Supplier`,
  "entity.shipment.supplierInteractionId": msg`Supplier interaction`,
  "entity.shipment.tags": msg`Tags`,
  "entity.shipment.trackingNumber": msg`Tracking number`,
  "entity.supplier": msg`Supplier`,
  "entity.supplier.accountManagerId": msg`Account manager`,
  "entity.supplier.assignee": msg`Assignee`,
  "entity.supplier.createdAt": msg`Created at`,
  "entity.supplier.createdBy": msg`Created by`,
  "entity.supplier.currencyCode": msg`Currency`,
  "entity.supplier.defaultCc": msg`Default cc`,
  "entity.supplier.fax": msg`Fax`,
  "entity.supplier.id": msg`Id`,
  "entity.supplier.intercompanyCompanyId": msg`Intercompany company`,
  "entity.supplier.logo": msg`Logo`,
  "entity.supplier.name": msg`Name`,
  "entity.supplier.phone": msg`Phone`,
  "entity.supplier.purchasingContactId": msg`Purchasing contact`,
  "entity.supplier.readableId": msg`Readable`,
  "entity.supplier.supplierStatus": msg`Status`,
  "entity.supplier.supplierTypeId": msg`Type`,
  "entity.supplier.tags": msg`Tags`,
  "entity.supplier.taxPercent": msg`Tax percent`,
  "entity.supplier.website": msg`Website`,
  "entity.user": msg`User`,
  "entity.user.about": msg`About`,
  "entity.user.acknowledgedITAR": msg`Acknowledged itar`,
  "entity.user.active": msg`Active`,
  "entity.user.admin": msg`Admin`,
  "entity.user.avatarUrl": msg`Avatar url`,
  "entity.user.createdAt": msg`Created at`,
  "entity.user.developer": msg`Developer`,
  "entity.user.email": msg`Email`,
  "entity.user.firstName": msg`First name`,
  "entity.user.flags": msg`Flags`,
  "entity.user.fullName": msg`Full name`,
  "entity.user.id": msg`Id`,
  "entity.user.isConsoleOperator": msg`Is console operator`,
  "entity.user.lastName": msg`Last name`,
  "entity.user.phone": msg`Phone`,
  "inventory.receiptPosted": msg`A receipt is posted`,
  "inventory.shipmentPosted": msg`A shipment is posted`,
  "invoicing.purchaseInvoicePosted": msg`A purchase invoice is posted`,
  "invoicing.salesInvoicePosted": msg`A sales invoice is posted`,
  "item.active.changed": msg`An item's active changes`,
  "item.assignee.changed": msg`An item's assignee changes`,
  "item.created": msg`An item is created`,
  "item.defaultMethodType.changed": msg`An item's default method type changes`,
  "item.deleted": msg`An item is deleted`,
  "item.itemTrackingType.changed": msg`An item's tracking type changes`,
  "item.name.changed": msg`An item's name changes`,
  "item.quantityOnHand": msg`Quantity on hand`,
  "item.replenishmentSystem.changed": msg`An item's replenishment system changes`,
  "item.revisionStatus.changed": msg`An item's revision status changes`,
  "item.unitOfMeasureCode.changed": msg`An item's unit of measure changes`,
  "item.update": msg`Update an item`,
  "job.assignee.changed": msg`A job's assignee changes`,
  "job.create": msg`Create a job`,
  "job.created": msg`A job is created`,
  "job.deadlineType.changed": msg`A job's deadline type changes`,
  "job.deleted": msg`A job is deleted`,
  "job.dueDate.changed": msg`A job's due date changes`,
  "job.earliestOperationStart": msg`Earliest operation start`,
  "job.latestOperationEnd": msg`Latest operation end`,
  "job.openOperationCount": msg`Number of open operations`,
  "job.operationCount": msg`Number of operations`,
  "job.priority.changed": msg`A job's priority changes`,
  "job.quantity.changed": msg`A job's quantity changes`,
  "job.scrapPercentage": msg`Scrap percentage`,
  "job.scrapQuantity.changed": msg`A job's scrap quantity changes`,
  "job.startDate.changed": msg`A job's start date changes`,
  "job.status.changed": msg`A job's status changes`,
  "job.totalScrapQuantity": msg`Total scrap quantity`,
  "job.update": msg`Update a job`,
  "nonConformance.assignee.changed": msg`An issue's assignee changes`,
  "nonConformance.closeDate.changed": msg`An issue's close date changes`,
  "nonConformance.create": msg`Create an issue`,
  "nonConformance.created": msg`An issue is created`,
  "nonConformance.deleted": msg`An issue is deleted`,
  "nonConformance.dueDate.changed": msg`An issue's due date changes`,
  "nonConformance.locationId.changed": msg`An issue's location changes`,
  "nonConformance.nonConformanceTypeId.changed": msg`An issue's type changes`,
  "nonConformance.openTaskCount": msg`Number of open tasks`,
  "nonConformance.priority.changed": msg`An issue's priority changes`,
  "nonConformance.quantity.changed": msg`An issue's quantity changes`,
  "nonConformance.source.changed": msg`An issue's source changes`,
  "nonConformance.status.changed": msg`An issue's status changes`,
  "nonConformance.update": msg`Update an issue`,
  notify: msg`Notify someone`,
  "operation.item.quantityOnHand.input.item": msg`Record`,
  "operation.job.earliestOperationStart.input.job": msg`Record`,
  "operation.job.latestOperationEnd.input.job": msg`Record`,
  "operation.job.openOperationCount.input.job": msg`Record`,
  "operation.job.operationCount.input.job": msg`Record`,
  "operation.job.scrapPercentage.input.job": msg`Record`,
  "operation.job.totalScrapQuantity.input.job": msg`Record`,
  "operation.nonConformance.openTaskCount.input.nonConformance": msg`Record`,
  "operation.purchaseOrder.lineCount.input.purchaseOrder": msg`Record`,
  "operation.purchaseOrder.total.input.purchaseOrder": msg`Record`,
  "operation.quote.total.input.quote": msg`Record`,
  "operation.receipt.lineCount.input.receipt": msg`Record`,
  "operation.salesOrder.lineCount.input.salesOrder": msg`Record`,
  "operation.salesOrder.total.input.salesOrder": msg`Record`,
  "operation.shipment.lineCount.input.shipment": msg`Record`,
  "production.jobHeld": msg`A job is put on hold`,
  "production.jobOperationCompleted": msg`A job operation is completed`,
  "production.jobReleased": msg`A job is released`,
  "purchaseOrder.assignee.changed": msg`A purchase order's assignee changes`,
  "purchaseOrder.create": msg`Create a purchase order`,
  "purchaseOrder.created": msg`A purchase order is created`,
  "purchaseOrder.deleted": msg`A purchase order is deleted`,
  "purchaseOrder.lineCount": msg`Number of lines`,
  "purchaseOrder.orderDate.changed": msg`A purchase order's order date changes`,
  "purchaseOrder.purchaseOrderType.changed": msg`A purchase order's type changes`,
  "purchaseOrder.status.changed": msg`A purchase order's status changes`,
  "purchaseOrder.supplierId.changed": msg`A purchase order's supplier changes`,
  "purchaseOrder.supplierLocationId.changed": msg`A purchase order's supplier location changes`,
  "purchaseOrder.supplierReference.changed": msg`A purchase order's supplier reference changes`,
  "purchaseOrder.tags.changed": msg`A purchase order's tags changes`,
  "purchaseOrder.total": msg`Total`,
  "purchaseOrder.update": msg`Update a purchase order`,
  "quote.assignee.changed": msg`A quote's assignee changes`,
  "quote.completedDate.changed": msg`A quote's completed date changes`,
  "quote.created": msg`A quote is created`,
  "quote.customerId.changed": msg`A quote's customer changes`,
  "quote.deleted": msg`A quote is deleted`,
  "quote.dueDate.changed": msg`A quote's due date changes`,
  "quote.estimatorId.changed": msg`A quote's estimator changes`,
  "quote.expirationDate.changed": msg`A quote's expiration date changes`,
  "quote.salesPersonId.changed": msg`A quote's salesperson changes`,
  "quote.status.changed": msg`A quote's status changes`,
  "quote.total": msg`Total`,
  "quote.update": msg`Update a quote`,
  "receipt.assignee.changed": msg`A receipt's assignee changes`,
  "receipt.created": msg`A receipt is created`,
  "receipt.deleted": msg`A receipt is deleted`,
  "receipt.invoiced.changed": msg`A receipt's invoiced changes`,
  "receipt.lineCount": msg`Number of lines`,
  "receipt.locationId.changed": msg`A receipt's location changes`,
  "receipt.postingDate.changed": msg`A receipt's posting date changes`,
  "receipt.sourceDocument.changed": msg`A receipt's source document changes`,
  "receipt.status.changed": msg`A receipt's status changes`,
  "receipt.supplierId.changed": msg`A receipt's supplier changes`,
  "receipt.update": msg`Update a receipt`,
  "sales.quoteAccepted": msg`A quote is accepted`,
  "sales.quoteSent": msg`A quote is sent`,
  "salesOrder.assignee.changed": msg`A sales order's assignee changes`,
  "salesOrder.completedDate.changed": msg`A sales order's completed date changes`,
  "salesOrder.create": msg`Create a sales order`,
  "salesOrder.created": msg`A sales order is created`,
  "salesOrder.customerId.changed": msg`A sales order's customer changes`,
  "salesOrder.customerReference.changed": msg`A sales order's customer reference changes`,
  "salesOrder.deleted": msg`A sales order is deleted`,
  "salesOrder.lineCount": msg`Number of lines`,
  "salesOrder.locationId.changed": msg`A sales order's location changes`,
  "salesOrder.orderDate.changed": msg`A sales order's order date changes`,
  "salesOrder.salesPersonId.changed": msg`A sales order's salesperson changes`,
  "salesOrder.status.changed": msg`A sales order's status changes`,
  "salesOrder.total": msg`Total`,
  "salesOrder.update": msg`Update a sales order`,
  "shipment.assignee.changed": msg`A shipment's assignee changes`,
  "shipment.created": msg`A shipment is created`,
  "shipment.customerId.changed": msg`A shipment's customer changes`,
  "shipment.deleted": msg`A shipment is deleted`,
  "shipment.lineCount": msg`Number of lines`,
  "shipment.locationId.changed": msg`A shipment's location changes`,
  "shipment.postingDate.changed": msg`A shipment's posting date changes`,
  "shipment.shippingMethodId.changed": msg`A shipment's shipping method changes`,
  "shipment.status.changed": msg`A shipment's status changes`,
  "shipment.trackingNumber.changed": msg`A shipment's tracking number changes`,
  "shipment.update": msg`Update a shipment`,
  "supplier.accountManagerId.changed": msg`A supplier's account manager changes`,
  "supplier.assignee.changed": msg`A supplier's assignee changes`,
  "supplier.created": msg`A supplier is created`,
  "supplier.currencyCode.changed": msg`A supplier's currency changes`,
  "supplier.deleted": msg`A supplier is deleted`,
  "supplier.name.changed": msg`A supplier's name changes`,
  "supplier.supplierStatus.changed": msg`A supplier's status changes`,
  "supplier.supplierTypeId.changed": msg`A supplier's type changes`,
  "supplier.taxPercent.changed": msg`A supplier's tax percent changes`,
  "supplier.update": msg`Update a supplier`,
  webhook: msg`Call an outside URL`
};
