/**
 * generate-agent-kb (docs/scripts) — build the in-app agent's read-only knowledge base from the docs site.
 *
 * The Fumadocs MDX under `docs/content/**` is the source of truth. The in-app agent
 * (apps/erp `modules/agent`) reads a flattened, component-stripped copy of every page from
 * `apps/erp/app/modules/agent/kb/<slug>.md`, plus a `manifest.json` keyword index that
 * `search_docs` scans. This script regenerates both and prunes stale files.
 *
 * The MDX→markdown stripping lives in `docs/lib/markdown-corpus.ts`, shared with the
 * public `/llms.txt` + `/llms-full.txt` routes so the agent corpus and the AI-crawler
 * corpus can never disagree about what a page says.
 *
 * Committed output ships inside the erp Docker image, so the agent reads it with a bundled
 * import / fs read at runtime (no docs-app dependency). Mirrors the `generate-mcp.ts` pattern.
 *
 * Run it manually after editing docs/content, and commit the regenerated kb/ alongside
 * the docs change — same model as filling .po files before a commit. The check-and-commit
 * skill runs it automatically when docs/content or this script is in the change set.
 * See .ai/rules/agent-knowledge-base.md.
 *
 * Run:  pnpm run generate:agent-kb
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { keywords, readCorpus } from "../lib/markdown-corpus";

// Paths resolve from this file's location, so the script works from any cwd
// (run via `pnpm run generate:agent-kb` at the repo root).
const DOCS_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = path.join(DOCS_ROOT, "..");
const CONTENT_DIR = path.join(DOCS_ROOT, "content");
const KB_DIR = path.join(ROOT, "apps/erp/app/modules/agent/kb");
const MANIFEST_PATH = path.join(KB_DIR, "manifest.json");

type ManifestEntry = {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  headings: string[];
};

function main() {
  const pages = readCorpus(CONTENT_DIR);
  const written = new Set<string>();
  const manifest: ManifestEntry[] = [];

  for (const page of pages) {
    const md = `# ${page.title}\n\n${
      page.description ? `> ${page.description}\n\n` : ""
    }${page.markdown}\n`;
    const outPath = path.join(KB_DIR, `${page.slug}.md`);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, md, "utf8");
    written.add(path.resolve(outPath));

    manifest.push({
      slug: page.slug,
      title: page.title,
      description: page.description,
      keywords: keywords(page.title, page.slug),
      headings: page.headings
    });
  }

  manifest.sort((a, b) => a.slug.localeCompare(b.slug));
  fs.mkdirSync(KB_DIR, { recursive: true });
  fs.writeFileSync(
    MANIFEST_PATH,
    `${JSON.stringify(
      {
        _comment:
          "GENERATED by docs/scripts/generate-agent-kb.ts from docs/content. Do not hand-edit — run `pnpm run generate:agent-kb`.",
        docs: manifest
      },
      null,
      2
    )}\n`,
    "utf8"
  );

  // Drop a README so nobody hand-edits this folder. Added to `written` so the
  // prune step below doesn't delete it.
  const readmePath = path.join(KB_DIR, "README.md");
  fs.writeFileSync(
    readmePath,
    `# Agent knowledge base (auto-generated — do not edit)

Every file in this folder is generated from the docs site (\`docs/content/**\`) by
\`docs/scripts/generate-agent-kb.ts\`. It is the read-only corpus the in-app agent searches
(\`search_docs\`) and reads (\`read_doc\`), bundled into the erp image so it ships with the app.

**Do not edit these files by hand — your changes will be overwritten.**

To update the content, edit the source docs under \`docs/content/\` and regenerate, then
commit the result **in the same commit** as the docs change (same model as filling \`.po\`
translations before committing):

\`\`\`bash
pnpm run generate:agent-kb
\`\`\`

The check-and-commit skill runs this automatically when \`docs/content/**\` or the generator
is in the change set. See \`.ai/rules/agent-knowledge-base.md\`.
`,
    "utf8"
  );
  written.add(path.resolve(readmePath));

  // Prune stale generated .md (source docs removed).
  const pruned: string[] = [];
  const walkKb = (dir: string) => {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walkKb(p);
        if (fs.readdirSync(p).length === 0) fs.rmdirSync(p);
      } else if (entry.name.endsWith(".md") && !written.has(path.resolve(p))) {
        fs.rmSync(p);
        pruned.push(path.relative(KB_DIR, p));
      }
    }
  };
  walkKb(KB_DIR);

  process.stdout.write(
    `Wrote ${manifest.length} docs -> ${path.relative(ROOT, KB_DIR)}\n`
  );
  process.stdout.write(`Manifest: ${path.relative(ROOT, MANIFEST_PATH)}\n`);
  if (pruned.length)
    process.stdout.write(
      `Pruned ${pruned.length} stale: ${pruned.join(", ")}\n`
    );
}

main();
