// Generated from migration-built local PostgreSQL by scripts/generate-types.ts. Do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
export type Database = {
  knowledge: {
    Tables: {
      audit: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          actorId: string | null;
          callerId: string;
          requestId: string;
          action: string;
          targetRefs: Json;
          decision: string;
          policyVersion: string;
          metadata: Json;
          legalHoldUntil: string | null;
          metadataPurgedAt: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          actorId?: string | null;
          callerId: string;
          requestId: string;
          action: string;
          targetRefs?: Json;
          decision: string;
          policyVersion: string;
          metadata?: Json;
          legalHoldUntil?: string | null;
          metadataPurgedAt?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          actorId?: string | null;
          callerId?: string;
          requestId?: string;
          action?: string;
          targetRefs?: Json;
          decision?: string;
          policyVersion?: string;
          metadata?: Json;
          legalHoldUntil?: string | null;
          metadataPurgedAt?: string | null;
        };
      };
      chunk: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          documentId: string;
          documentVersionId: string;
          ordinal: number;
          text: string;
          heading: string | null;
          page: number | null;
          bounds: Json | null;
          parentOrdinal: number | null;
          tokenCount: number;
          fts: string | null;
          embedding: string | null;
          embeddingProfile: string;
          indexGeneration: string;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          documentId: string;
          documentVersionId: string;
          ordinal: number;
          text: string;
          heading?: string | null;
          page?: number | null;
          bounds?: Json | null;
          parentOrdinal?: number | null;
          tokenCount: number;
          embedding?: string | null;
          embeddingProfile: string;
          indexGeneration: string;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          documentId?: string;
          documentVersionId?: string;
          ordinal?: number;
          text?: string;
          heading?: string | null;
          page?: number | null;
          bounds?: Json | null;
          parentOrdinal?: number | null;
          tokenCount?: number;
          embedding?: string | null;
          embeddingProfile?: string;
          indexGeneration?: string;
        };
      };
      command: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          actorId: string;
          action: string;
          targetSourceId: string;
          targetResourceId: string;
          payload: Json;
          payloadHash: string;
          proposalVersion: string;
          idempotencyKey: string;
          status: string;
          executeAt: string | null;
          resultRef: Json | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          actorId: string;
          action: string;
          targetSourceId: string;
          targetResourceId: string;
          payload?: Json;
          payloadHash: string;
          proposalVersion?: string;
          idempotencyKey: string;
          status?: string;
          executeAt?: string | null;
          resultRef?: Json | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          actorId?: string;
          action?: string;
          targetSourceId?: string;
          targetResourceId?: string;
          payload?: Json;
          payloadHash?: string;
          proposalVersion?: string;
          idempotencyKey?: string;
          status?: string;
          executeAt?: string | null;
          resultRef?: Json | null;
        };
      };
      conversation: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          ownerId: string;
          compactState: Json;
          expiresAt: string;
          legalHoldUntil: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          ownerId: string;
          compactState?: Json;
          expiresAt: string;
          legalHoldUntil?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          ownerId?: string;
          compactState?: Json;
          expiresAt?: string;
          legalHoldUntil?: string | null;
        };
      };
      document: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          sourceId: string;
          sourceItemId: string;
          title: string;
          ownerId: string;
          kind: string;
          status: string;
          classification: string;
          aclVersion: string;
          currentVersionId: string | null;
          deletedAt: string | null;
          legalHoldUntil: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId: string;
          sourceItemId: string;
          title: string;
          ownerId: string;
          kind: string;
          status?: string;
          classification: string;
          aclVersion?: string;
          currentVersionId?: string | null;
          deletedAt?: string | null;
          legalHoldUntil?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string;
          sourceItemId?: string;
          title?: string;
          ownerId?: string;
          kind?: string;
          status?: string;
          classification?: string;
          aclVersion?: string;
          currentVersionId?: string | null;
          deletedAt?: string | null;
          legalHoldUntil?: string | null;
        };
      };
      documentVersion: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          documentId: string;
          sourceRevision: string;
          contentHash: string;
          objectKey: string;
          objectGeneration: string;
          MIME: string;
          byteCount: string;
          extractedTextKey: string | null;
          observedAt: string;
          effectiveAt: string | null;
          parserVersion: string;
          extractionStatus: string;
          contentPurgedAt: string | null;
          reviewedMetadata: Json;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          documentId: string;
          sourceRevision: string;
          contentHash: string;
          objectKey: string;
          objectGeneration: string;
          MIME: string;
          byteCount: string;
          extractedTextKey?: string | null;
          observedAt: string;
          effectiveAt?: string | null;
          parserVersion: string;
          extractionStatus: string;
          contentPurgedAt?: string | null;
          reviewedMetadata?: Json;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          documentId?: string;
          sourceRevision?: string;
          contentHash?: string;
          objectKey?: string;
          objectGeneration?: string;
          MIME?: string;
          byteCount?: string;
          extractedTextKey?: string | null;
          observedAt?: string;
          effectiveAt?: string | null;
          parserVersion?: string;
          extractionStatus?: string;
          contentPurgedAt?: string | null;
          reviewedMetadata?: Json;
        };
      };
      entity: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          sourceId: string;
          sourceEntityId: string;
          entityType: string;
          sourceRevision: string;
          displayName: string;
          exactIdentifiers: Json;
          metadata: Json;
          observedAt: string;
          deletedAt: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId: string;
          sourceEntityId: string;
          entityType: string;
          sourceRevision: string;
          displayName: string;
          exactIdentifiers?: Json;
          metadata?: Json;
          observedAt: string;
          deletedAt?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string;
          sourceEntityId?: string;
          entityType?: string;
          sourceRevision?: string;
          displayName?: string;
          exactIdentifiers?: Json;
          metadata?: Json;
          observedAt?: string;
          deletedAt?: string | null;
        };
      };
      entityLink: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          entityId: string;
          documentId: string;
          documentVersionId: string | null;
          relation: string;
          applicability: Json;
          verifiedBy: string | null;
          verifiedAt: string | null;
          provenance: Json;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          entityId: string;
          documentId: string;
          documentVersionId?: string | null;
          relation: string;
          applicability?: Json;
          verifiedBy?: string | null;
          verifiedAt?: string | null;
          provenance?: Json;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          entityId?: string;
          documentId?: string;
          documentVersionId?: string | null;
          relation?: string;
          applicability?: Json;
          verifiedBy?: string | null;
          verifiedAt?: string | null;
          provenance?: Json;
        };
      };
      extraction: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          intakeId: string;
          generation: string;
          providerProfile: string;
          sourceVersions: Json;
          output: Json;
          status: string;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          intakeId: string;
          generation: string;
          providerProfile: string;
          sourceVersions?: Json;
          output?: Json;
          status: string;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          intakeId?: string;
          generation?: string;
          providerProfile?: string;
          sourceVersions?: Json;
          output?: Json;
          status?: string;
        };
      };
      grant: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          sourceId: string;
          documentId: string | null;
          entityId: string | null;
          subjectKind: string;
          subjectId: string;
          capability: string;
          origin: string;
          sourcePermissionId: string | null;
          policyVersion: string;
          validUntil: string | null;
          revokedAt: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId: string;
          documentId?: string | null;
          entityId?: string | null;
          subjectKind: string;
          subjectId: string;
          capability: string;
          origin: string;
          sourcePermissionId?: string | null;
          policyVersion: string;
          validUntil?: string | null;
          revokedAt?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string;
          documentId?: string | null;
          entityId?: string | null;
          subjectKind?: string;
          subjectId?: string;
          capability?: string;
          origin?: string;
          sourcePermissionId?: string | null;
          policyVersion?: string;
          validUntil?: string | null;
          revokedAt?: string | null;
        };
      };
      groupMembership: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          sourceId: string | null;
          groupId: string;
          memberUserId: string;
          origin: string;
          observedAt: string;
          validUntil: string;
          revokedAt: string | null;
          policyVersion: string;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string | null;
          groupId: string;
          memberUserId: string;
          origin: string;
          observedAt: string;
          validUntil: string;
          revokedAt?: string | null;
          policyVersion: string;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string | null;
          groupId?: string;
          memberUserId?: string;
          origin?: string;
          observedAt?: string;
          validUntil?: string;
          revokedAt?: string | null;
          policyVersion?: string;
        };
      };
      identityBinding: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          issuer: string;
          subject: string;
          canonicalUserId: string;
          active: boolean;
          revocationVersion: string;
          capabilities: Array<string>;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          issuer: string;
          subject: string;
          canonicalUserId: string;
          active?: boolean;
          revocationVersion?: string;
          capabilities?: Array<string>;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          issuer?: string;
          subject?: string;
          canonicalUserId?: string;
          active?: boolean;
          revocationVersion?: string;
          capabilities?: Array<string>;
        };
      };
      intake: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          sourceId: string;
          ownerId: string;
          state: string;
          inputRefs: Json;
          generation: string;
          extraction: Json;
          reviewDecisions: Json;
          unresolved: Json;
          idempotencyKey: string;
          legalHoldUntil: string | null;
          rawPurgedAt: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId: string;
          ownerId: string;
          state?: string;
          inputRefs?: Json;
          generation?: string;
          extraction?: Json;
          reviewDecisions?: Json;
          unresolved?: Json;
          idempotencyKey: string;
          legalHoldUntil?: string | null;
          rawPurgedAt?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string;
          ownerId?: string;
          state?: string;
          inputRefs?: Json;
          generation?: string;
          extraction?: Json;
          reviewDecisions?: Json;
          unresolved?: Json;
          idempotencyKey?: string;
          legalHoldUntil?: string | null;
          rawPurgedAt?: string | null;
        };
      };
      outbox: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          sourceId: string;
          entityType: string;
          entityId: string;
          sourceVersion: string;
          eventType: string;
          payload: Json;
          availableAt: string;
          deliveredAt: string | null;
          attempts: number;
          leaseOwner: string | null;
          leaseUntil: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId: string;
          entityType: string;
          entityId: string;
          sourceVersion: string;
          eventType: string;
          payload?: Json;
          availableAt?: string;
          deliveredAt?: string | null;
          attempts?: number;
          leaseOwner?: string | null;
          leaseUntil?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string;
          entityType?: string;
          entityId?: string;
          sourceVersion?: string;
          eventType?: string;
          payload?: Json;
          availableAt?: string;
          deliveredAt?: string | null;
          attempts?: number;
          leaseOwner?: string | null;
          leaseUntil?: string | null;
        };
      };
      source: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          kind: string;
          externalId: string;
          displayName: string;
          ownerId: string;
          classification: string;
          providerPolicy: Json;
          status: string;
          contentEpoch: string;
          aclEpoch: string;
          cursor: Json | null;
          legalHoldUntil: string | null;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          kind: string;
          externalId: string;
          displayName: string;
          ownerId: string;
          classification: string;
          providerPolicy?: Json;
          status?: string;
          contentEpoch?: string;
          aclEpoch?: string;
          cursor?: Json | null;
          legalHoldUntil?: string | null;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          kind?: string;
          externalId?: string;
          displayName?: string;
          ownerId?: string;
          classification?: string;
          providerPolicy?: Json;
          status?: string;
          contentEpoch?: string;
          aclEpoch?: string;
          cursor?: Json | null;
          legalHoldUntil?: string | null;
        };
      };
      sourceUserBinding: {
        Row: {
          id: string;
          companyId: string;
          createdBy: string;
          createdAt: string;
          updatedBy: string | null;
          updatedAt: string | null;
          version: string;
          sourceId: string;
          canonicalUserId: string;
          sourceUserId: string;
          active: boolean;
          bindingEvidence: Json;
        };
        Insert: {
          id?: string;
          companyId: string;
          createdBy: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId: string;
          canonicalUserId: string;
          sourceUserId: string;
          active?: boolean;
          bindingEvidence?: Json;
        };
        Update: {
          id?: string;
          companyId?: string;
          createdBy?: string;
          createdAt?: string;
          updatedBy?: string | null;
          updatedAt?: string | null;
          version?: string;
          sourceId?: string;
          canonicalUserId?: string;
          sourceUserId?: string;
          active?: boolean;
          bindingEvidence?: Json;
        };
      };
    };
  };
};
